---
type: yml
auth:
  sign_key: hello


mysql:
  port: 3310
  host: localhost
  db_name: brainBlitz_db

redis:
  port: 6380
  host: localhost
  db: 0
  password: ""


matchMaking:
  waiting_timeout: "5m"
  mint_time_list_selection: "-2h"
  presence_prefix: "presence"

presence_service:
  Prefix: "presence"
  expiration_time: "60m"

scheduler:
  match_user_time_out: "1m"
