---
type: yml
auth:
  sign_key: hello

http:
  port: 8080
  infraPort: 8094

mysql:
  user: bbGame
  port: 3310
  host: localhost
  name: brainBlitz_db
  password: root
  maxlifetimeminutes: 3
  maxopencons: 10
  maxidlecons: 1
  retry: 5s

mongo:
  user: mongodb
  host: localhost
  port: 27018

redis:
  port: 6380
  host: "localhost"
  db: 0
  password: ""


matchMaking:
  waiting_timeout: "20m"
  least_presence: "-20m"
  mint_time_list_selection: "-20m"

presence_service:
  Prefix: "presence"
  expiration_time: "60m"

presence:
  presence_prefix: "presence"

scheduler:
  match_user_time_out: "1m"

kafka:
  host: "kafka"
  port: "9092"

feature:
  Infra: true
  metrics: true
