---
type: yml
auth:
  sign_key: hello


mysql:
  port: 3310
  host: localhost
  db_name: brainBlitz_db

redis:
  port: 6379
  host: BrainBlitz-redis
  db: 0
  password: ""


matchMaking:
  waiting_timeout: "2m"
  least_presence: "-2m"
  mint_time_list_selection: "-2m"

presence_service:
  Prefix: "presence"
  expiration_time: "60m"

presence:
  presence_prefix: "presence"

scheduler:
  match_user_time_out: "1m"

kafka:
  host: "kafka"
  port: "9092"
